name: 检查 Bash 权限

# 可通过手动触发，也可以改为 push、pull_request 等事件
on:
  workflow_dispatch:

jobs:
  inspect-permissions:
    runs-on: self-hosted

    steps:
      - name: 输出当前用户信息
        run: |
          echo "当前用户名：$(whoami)"
          echo "UID/GID 详情："
          id

      - name: 查看 Bash 进程所属用户／组
        run: |
          echo "当前 Shell 进程 PID: $$"
          echo "所属用户／UID／GID／命令："
          ps -p $$ -o user,uid,gid,cmd

      - name: 查看 Bash 可执行文件权限
        run: |
          BASH_PATH=$(which bash)
          echo "Bash 路径：${BASH_PATH}"
          echo "文件权限及属主："
          ls -lh "${BASH_PATH}"
          echo "更详细的文件元数据："
          stat "${BASH_PATH}"
