name: "Needs CI (with secrets)"
on:
  pull_request_target:
    types: [labeled]

jobs:
  privileged-test:
    if: ${{ github.event.label.name == 'needs-ci' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3
        with:
          # pull_request_target 默认签出当前主仓库的 HEAD，
          # 要改成 PR 分支：
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Show that we have MY_SECRET
        run: echo "✅ MY_SECRET is ${{ secrets.MY_SECRET }}"
