name: "Request CI (no secrets)"
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Show runner and PR info
        run: |
          echo "Event: ${{ github.event_name }}#${{ github.event.action }}"
          echo "Head repo: ${{ github.event.pull_request.head.repo.full_name }}"
      - name: Try to read SECRET (`MY_SECRET`)
        run: |
          if [ -z "${{ secrets.MY_SECRET }}" ]; then
            echo "⚠️ MY_SECRET is empty (as expected for pull_request)"
          else
            echo "❌ MY_SECRET is: ${{ secrets.MY_SECRET }}"
          fi
