name: Secret and Artifact Leakage Test

on:
  workflow_dispatch:

jobs:
  test-cache:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: .pip_cache
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Install Python Dependencies
        env:
          PIP_CACHE_DIR: .pip_cache
        run: |
          if [ -f requirements.txt ]; then
            pip install --cache-dir .pip_cache -r requirements.txt
          else
            echo "No requirements.txt found. Skipping pip install."
          fi
